server:
  port: 8080

spring:
  application:
    name: ecom-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
